openapi: 3.0.2
info:
  title: Ping API
  version: 1.0.0

paths:
  /a:
    get:
      tags:
        - get
      responses:
        'default':
          description: none

#    private Operation get = null;
#    private Operation put = null;
#    private Operation post = null;
#    private Operation delete = null;
#    private Operation options = null;
#    private Operation head = null;
#    private Operation patch = null;
#    private Operation trace = null;
