title: openapi-processor-spring

description: >-
  an openapi-processor for spring-boot

url: "https://hauner.github.io"
baseurl: "/openapi-processor-spring"

twitter_username: "@MartinHauner"
github_username:  hauner

remote_theme: pmarsceill/just-the-docs

exclude:
  - README.md
  - SCRATCH.md
  - api.md
  - gradle-obsolete.md

include:
  - ../images

##
## "just-the-docs" theme options
##
search_enabled: true
search_tokenizer_separator: /[\s/]+/

# logo, replaces the title
logo: "https://github.com/hauner/openapi-processor-spring/raw/master/images/openapi-processor-spring%40400x200.png"

aux_links:
  openapi-processor-spring:
    - //github.com/hauner/openapi-processor-spring

#footer_content:
